#define TABLECRAWL_NONE 0
#define TABLECRAWL_ATTEMPTING 1
#define TABLECRAWL_PENDING 2
#define TABLECRAWL_UNDER 3

#define TABLE_CRAWL_BONK_STUN (5 SECONDS)
#define TABLE_CRAWL_BONK_COOLDOWN (1 SECONDS)
#define TABLE_CRAWL_BONK_SOUND_VOLUME 100
#define TABLE_CRAWL_ACTION_WARNING_COOLDOWN (1 SECONDS)
#define TABLE_CRAWL_FULLSCREEN_CATEGORY "table_crawl_view"
#define TABLE_CRAWL_UNDER_LAYER_OFFSET 0.1
